### ISSUE TITLE
Need to state somewhere that the package would work only with Node.js v10.12.0 and higher

### ISSUE THREAD

**Issue by YuryStrozhevsky** [PeculiarVentures/webcrypto#12]
Was running it on Node.js v8.6 and got error
```console
TypeError: crypto.generateKeyPairSync is not a function
```
So, it is necessary to state somewhere in docs that the package would work only with Node v10.12.0 and higher. Or redesign the package by removing `generateKeyPairSync` usage.

**Comment by microshine** [comment]
@YuryStrozhevsky Thank you. I've added a description to README file and `engines` condition to package.json

New version `@peculiar/webcrypto@1.0.12` is available

**Comment by YuryStrozhevsky** [comment]
@microshine No chance to prevent usage of v10 API and downgrade restirctions to v8 version, for example?

**Comment by microshine** [comment]
It's not possible cause downgrade versions haven't got generate key functions for `RSA` and `EC` algorithms.

**Comment by CxRes** [comment]
Should the engines value not be `>=10.12.0` as pointed out above and in light of https://github.com/nodejs/node/blob/v10.x/doc/changelogs/CHANGELOG_V10.md#10.12.0
