### ISSUE TITLE
Error: Wrong parameter: inputBuffer must be "ArrayBuffer"  at `crypto.subtle.exportKey` in a nwjs environment but not in node

### ISSUE THREAD

**Issue by CxRes** [PeculiarVentures/webcrypto#17]
I am hitting the following error in an nw.js (which is an electron like) environment:
```sh
Error: Wrong parameter: inputBuffer must be "ArrayBuffer" 
    at Function.parse 
    at RsaPublicKey.getKey 
    at RsaPublicKey.toJSON
    at Function.toJSON 
    at Function.exportKey 
    at RsaSsaProvider.onExportKey 
    at RsaSsaProvider.exportKey 
    at SubtleCrypto.exportKey 
    at crypto.subtle.generateKey.then 
```
(Sorry about the line numbers, I am pulling these out of a bundle and sourcemaps are giving me grief)

The happens at `crypto.subtle.exportKey` in the snippet below. This is despite the fact that the key is being generated by this library itself. The key is generated and exported using the following code:
```js
static generateSessionKeys () {
    return crypto.subtle.generateKey(
      {
        name: "RSASSA-PKCS1-v1_5",
        modulusLength: 2048,
        publicExponent: new Uint8Array([0x01, 0x00, 0x01]),
        hash: { name: "SHA-256" },
      },
      true,
      ["sign", "verify"]
    )
      .then((keyPair) => {
        // returns a keypair object
        return Promise.all([
          crypto.subtle.exportKey('jwk', keyPair.publicKey),
          crypto.subtle.exportKey('jwk', keyPair.privateKey)
        ])
      })
  }
```

**Comment by rmhrisk** [comment]
Can you create a small project to reproduce? There’s just not enough to go on.

**Comment by CxRes** [comment]
I have traced down the error and it is environment specific to NW.js. [NW.js messes with global objects](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/#working-with-multiple-contexts) as a result of which `instanceof` operator does not work in many instances. The error here is a direct result of `instanceof` check failing on the `inputbuffer` object. 

I had forgotten about this quirk... sorry about the issue!
