### ISSUE TITLE
Need to implement OAEP encryption

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/webcrypto#2]
We are currently blocked on implementing RSA OAEP based encryption by this bug:
https://github.com/nodejs/help/issues/1726. Without this, we will not be able to deprecate the `node-webcrypto-ossl` library.

**Comment by LiraNuna** [comment]
Is it possible to support OAEP without label currently as it's optional? A note can be added.

**Comment by microshine** [comment]
I think yes

**Comment by microshine** [comment]
Fixed in v1.0.12
