### ISSUE TITLE
license mit vs all rights reserved

### ISSUE THREAD

**Issue by chase-moskal** [PeculiarVentures/webcrypto#20]
i noticed the es module has an "all rights reserved" banner, which is in seeming conflict with the MIT license presented at the project root

https://github.com/PeculiarVentures/webcrypto/blob/47976a9b35fcdbb42e045cb3ba5b9626bed620a5/rollup.config.js#L6

**Comment by rmhrisk** [comment]
SHOULD BE:
Copyright (c) 2020 Peculiar Ventures, LLC

PR welcomed

**Comment by microshine** [comment]
Fixed
