### ISSUE TITLE
Node.js package

### ISSUE THREAD

**Issue by pantchox** [PeculiarVentures/webcrypto#27]
Hi,
thanks for this great wrapper.

I think from node version 15.14.0 there is webcrypto in the official crytpo library.
like so: `require('crypto').webcrypto`
this might be a good idea to offer isomorphic package.

thanks!

**Comment by microshine** [comment]
`@peculiar/webcrypto` implements some extra mechanisms which are not specified in WebCrypto API

See [supported mechanisms table](https://github.com/PeculiarVentures/webcrypto#supported-algorithms)

**Comment by pantchox** [comment]
As long that it pollyfill web crypto it is fine, adding that will help as well.
