### ISSUE TITLE
ArrayBufferViews aren't always aligned with their ArrayBuffer

### ISSUE THREAD

**Issue by reidrankin** [PeculiarVentures/webcrypto#35]
ArrayBufferViews are not required to be aligned with their underlying `.buffer` property. Instead of:

https://github.com/PeculiarVentures/webcrypto/blob/012a63f17f3e67e91219ecb8a4eeee2c7d81dc0c/src/crypto.ts#L10

do:
```
const buffer = Buffer.from(array.buffer, array.byteOffset, array.byteLength)
```

**Comment by microshine** [comment]
@reidrankin The new version `@peculiar/webcrypto@1.2.2` has been published

**Comment by reidrankin** [comment]
Thanks!
