### ISSUE TITLE
`oct` JWK should not require alg during importKey

### ISSUE THREAD

**Issue by panva** [PeculiarVentures/webcrypto#37]
The HmacCryptoKey and AesCryptoKey interfaces wrongfully require the `alg` attribute to be present when importing keyData in `jwk` key format.

Every other webcrypto runtime allows these to omitted and in order to have interoperable behaviour between runtimes it is in fact better to remove the `alg` attribute.

**Comment by microshine** [comment]
Looks like Chrome compares `key_ops` and `alg` with incoming parameters if those fields present in JWK
![image](https://user-images.githubusercontent.com/7333669/141021956-194ef2a3-3b9c-4215-b8cf-802e99ecb32d.png)

I'll fix it

**Comment by microshine** [comment]
@panva The new version `@peculiar/webcrypto@1.2.1` has been published

**Comment by panva** [comment]
@microshine confirmed, thank you!
