### ISSUE TITLE
[webview-crypto] error in `parse` of message & ReferenceError: Property 'abvs' doesn't exist

### ISSUE THREAD

**Issue by 3210jr** [PeculiarVentures/webcrypto#39]
Hey all!

I am trying to get the package to work with react-native and gundb but facing a couple of errors and warnings. Below is one of the more confusing warnings I am getting. Hopefully someone recognizes it and offers some insight. 

`
[webview-crypto] error in `parse` of message: "%7B%22id%22%3A%22c510-9fc9-53c0-72ed-63de-5b05-7515-35a7%22%2C%22value%22%3A%7B%22__serializer_id%22%3A%22CryptoKey%22%2C%22value%22%3A%7B%22serialized%22%3Atrue%2C%22_import%22%3A%7B%22format%22%3A%22raw%22%2C%22keyData%22%3A%7B%22__serializer_id%22%3A%22ArrayBufferView%22%2C%22value%22%3A%7B%22name%22%3A%22Uint8Array%22%2C%22buffer%22%3A%7B%22__serializer_id%22%3A%22ArrayBuffer%22%2C%22value%22%3A%22password%22%7D%7D%7D%7D%2C%22type%22%3A%22secret%22%2C%22extractable%22%3Afalse%2C%22algorithm%22%3A%7B%22name%22%3A%22PBKDF2%22%7D%2C%22usages%22%3A%5B%22deriveBits%22%5D%7D%7D%7D" reason: {"name":"ReferenceError","message":"Property 'abvs' doesn't exist","stack":"ReferenceError: Property 'abvs' doesn't exist\n    at eval (JavaScript:1:16)\n    at anonymous
`

Thanks!

**Comment by ngima** [comment]
Any update?
