### ISSUE TITLE
Missing Algorithm: AES-KW

### ISSUE THREAD

**Issue by LiraNuna** [PeculiarVentures/webcrypto#4]
This algorithm is missing from this library. I would love to use it, but since AES-KW is required for JOSE for both ECDH-ES and PKES2 based key wrapping, I can't.

Would you accept a PR if I try to tackle this?

**Comment by rmhrisk** [comment]
Can you explain the approach you would take?

**Comment by LiraNuna** [comment]
So far as I understand, webcrypto-core covers most of the input validation and routing to the providers. I already got import/export working easily by creating a new provider. 

As for the algorithm itself, I am certain NodeJS already supports AES-KW via `crypto.createDecipheriv`.  I know that the cipher name via OSSL is `id-aesXXX-wrap` (where XXX is the key size) with IV of `A6A6A6A6A6A6A6A6` hex.

You can track my progress with this PR: https://github.com/LiraNuna/webcrypto/pull/1

**Comment by microshine** [comment]
@LiraNuna I've updated `webcrypto` a bit. Please sync you code with the latest version.
You can use `wrappedKey` test param for AES-KW wrapped key checking ([example](https://github.com/PeculiarVentures/webcrypto/blob/master/test/aes.ts#L92))

**Comment by microshine** [comment]
@LiraNuna If your PR is done, I can accept it and publish new version to `npm`

**Comment by LiraNuna** [comment]
Is that the binary of the 'expected encrypted key'?

**Comment by microshine** [comment]
yes

**Comment by LiraNuna** [comment]
Just updated PR #5 with 3 of the test vectors from RFC 3394.
