### ISSUE TITLE
Fails to build with the latest typescript

### ISSUE THREAD

**Issue by styfle** [PeculiarVentures/webcrypto#44]
## Problem

TypeScript 4.6.2 was just released and added `crypto.randomUUID()` in https://github.com/microsoft/TypeScript/commit/4e689bc075974bd1f70c00adc1df5634846e734e

This causes `@peculiar/webcrypto` to fail to build.

## Steps to reproduce

Create a new project and install the latest dependencies.

```sh
mkdir example
cd example
npm init -y
npm install @peculiar/webcrypto@1.3.0 typescript@4.6.2
echo '{ "compilerOptions": { "module": "commonjs" } }' > tsconfig.json
echo 'import { Crypto } from "@peculiar/webcrypto"' > index.ts
./node_modules/.bin/tsc
```

## Error

```
@peculiar/webcrypto/index.d.ts:1:22 - error TS2420: Class 'import("@peculiar/webcrypto/index").Crypto' incorrectly implements interface 'Crypto'.
  Property 'randomUUID' is missing in type 'import("@peculiar/webcrypto/index").Crypto' but required in type 'Crypto'.

1 export declare class Crypto implements globalThis.Crypto {
                       ~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:3652:5
    3652     randomUUID(): string;
```

**Comment by microshine** [comment]
Working on it

**Comment by microshine** [comment]
@styfle Please try `@peculiar/webcrypto@1.3.1`. It implements the missed `Crypto::randomUUID` method and uses the `@types/web` type definition file instead of the default `lib-dom`.

**Comment by styfle** [comment]
It works now, thanks!
